services:
  - type: web
    name: resume-generator
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
